variables:
  MAKE: make
  GIT_DEPTH: 100

stages:
  - prebuild
  - cross_build


# Default cross build jobs that are always run
.cross_build_default_job_template: &cross_build_default_job_definition
  stage: cross_build
  script:
    - mkdir build
    - cd build
    - ../autogen.sh $CONFIGURE_OPTS || (cat config.log && exit 1)
    - $MAKE -j $(getconf _NPROCESSORS_ONLN)

# Extra cross build jobs that are only run post-merge, or
# when code is pushed to a branch with "ci-full-" name prefix
.cross_build_extra_job_template: &cross_build_extra_job_definition
  <<: *cross_build_default_job_definition
  only:
    - master
    - /^ci-full-.*$/


armv6l-debian-9:
  <<: *cross_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-9-cross-armv6l:latest

mips64el-debian-9:
  <<: *cross_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-9-cross-mips64el:latest

mips-debian-9:
  <<: *cross_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-9-cross-mips:latest

aarch64-debian-10:
  <<: *cross_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-10-cross-aarch64:latest

ppc64le-debian-10:
  <<: *cross_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-10-cross-ppc64le:latest

s390x-debian-10:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-10-cross-s390x:latest

armv7l-debian-sid:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-sid-cross-armv7l:latest

i686-debian-sid:
  <<: *cross_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-sid-cross-i686:latest

mipsel-debian-sid:
  <<: *cross_build_extra_job_definition
  image: quay.io/libvirt/buildenv-libvirt-debian-sid-cross-mipsel:latest

mingw32-fedora-30:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-30-cross-mingw32:latest

mingw64-fedora-30:
  <<: *cross_build_default_job_definition
  image: quay.io/libvirt/buildenv-libvirt-fedora-30-cross-mingw64:latest


# This artifact published by this job is downloaded by libvirt.org to
# be deployed to the web root:
#    https://gitlab.com/libvirt/libvirt/-/jobs/artifacts/master/download?job=website
website:
  stage: prebuild
  script:
    - mkdir build
    - cd build
    - ../autogen.sh --prefix=$(pwd)/../vroot || (cat config.log && exit 1)
    - $MAKE -j $(getconf _NPROCESSORS_ONLN) -C docs
    - $MAKE -j $(getconf _NPROCESSORS_ONLN) -C docs install
    - cd ..
    - mv vroot/share/doc/libvirt/html/ website
  image: quay.io/libvirt/buildenv-libvirt-fedora-31:latest
  artifacts:
    expose_as: 'Website'
    name: 'website'
    when: on_success
    expire_in: 30 days
    paths:
      - website
